wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: darkslateblue 
    checked: yellow
    highlight: 
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    columns: [40, 40, 50, 40]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    rows: [8, 8, 8, 8, 5]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    # You can have multiple widgets of the same type.
    # The "key" is the name of the widget and the type is the actual
    # widget you want to implement.
    europe_time:
      title: "Europe"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Paris: "Europe/Paris"
        London: "Europe/London"
        Montreal: "America/Montreal"
        New_York: "America/New_York"
        Chicago: "America/Chicago"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    americas_time:
      title: "Americas"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Vancouver: "America/Vancouver"
        Denver: "America/Denver"
        Sao_Paulo: "America/Sao_Paulo"
        Africa: "Africa/Dakar"
        Moscow: "Europe/Moscow"
        Shangai: "Asia/Shanghai"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    todolist:
      type: todo
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 3600
    ip:
      type: ipinfo
      title: "My IP"
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 150
    news:
      type: hackernews
      title: "HackerNews"
      enabled: true
      numberOfStories: 10
      position:
        top: 1
        left: 1
        height: 1
        width: 2
      storyType: top
      refreshInterval: 900
    Cheatsheet1:
      enabled: true
      type: textfile
      filePath: "/opt/resources/Cheatsheet1.txt"
      format: true
      position:
        top: 2
        left: 0
        height: 3
        width: 2
      refreshInterval: 30
      wrapText: false
    Cheatsheet2:
      enabled: true
      type: textfile
      filePath: "/opt/resources/Cheatsheet2.txt"
      format: true
      position:
        top: 2
        left: 2
        height: 3
        width: 2
      refreshInterval: 30
      wrapText: false
    github:
      type: github 
      apiKey: "1d961f877b41fed94eb1be4f64a83ac3815c4b5a"
      baseURL: "https://api.github.com"
      enabled: true
      enableStatus: true
      position:
        top: 0
        left: 3
        height: 2
        width: 1
      refreshInterval: 300
      repositories:
        - "TheThingGoesSkra/Kali-Tools-Installation-V2"
        - "TheThingGoesSkra/Web-Scripts"
        - "TheThingGoesSkra/sslstrip3"
      uploadURL: "https://api.github.com"
      username: "TheThingGoesSkra"
